import HTMLWebpackPlugin from "html-webpack-plugin";
import {ScriptTagCrossOriginPlugin} from "./script-tag-crossorigin-plugin";
import type {RspackPluginInstance} from "@rspack/core";
import type {HTMLEntryDescriptor} from "../../type";
import {WebpackConfigSerializationUtil} from "../WebpackConfigSerializationUtil";

interface HTMLPluginOptions {
    entry: HTMLEntryDescriptor;
}

/**
 * Creates a html file from a template with <script> and <link> injected
 * with the respective hashed output filenames.
 */
export function htmlPlugin({entry}: HTMLPluginOptions): RspackPluginInstance {
    return WebpackConfigSerializationUtil.serializablePlugin("HTMLWebpackPlugin", HTMLWebpackPlugin, {
        template: entry.htmlPath,
        filename: `${entry.name}.html`,
        chunks: [entry.name],
        minify: {
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            includeAutoGeneratedTags: false,
            keepClosingSlash: true,
            minifyCSS: true,
            minifyJS: true,
            minifyURLs: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            removeTagWhitespace: true,
            useShortDoctype: true,
        },
    });
}

/**
 * Adds attributes to `<script>` tag inside html file generated by
 * HTMLWebpackPlugin. Used to add `crossorigin="anonymous"`.
 */
export function scriptTagCrossOriginPlugin(): RspackPluginInstance {
    return WebpackConfigSerializationUtil.serializablePlugin("ScriptTagCrossOriginPlugin", ScriptTagCrossOriginPlugin);
}
