import HTMLWebpackPlugin from "html-webpack-plugin";
import ScriptExtHtmlWebpackPlugin from "script-ext-html-webpack-plugin";
import type webpack from "webpack";
import type {HTMLEntry} from "../../type";

interface HtmlPluginOptions {
    entry: HTMLEntry;
}

/**
 * Creates a html file from a template with <script> and <link> injected
 * with the respective hashed output filenames.
 */
export function htmlPlugin({entry}: HtmlPluginOptions): webpack.WebpackPluginInstance {
    return new HTMLWebpackPlugin({
        template: entry.htmlPath,
        filename: `${entry.name}.html`,
        chunks: [entry.name],
        minify: {
            collapseBooleanAttributes: true,
            collapseInlineTagWhitespace: true,
            collapseWhitespace: true,
            includeAutoGeneratedTags: false,
            keepClosingSlash: true,
            minifyCSS: true,
            minifyJS: true,
            minifyURLs: true,
            removeAttributeQuotes: true,
            removeComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true,
            removeTagWhitespace: true,
            useShortDoctype: true,
        },
    });
}

/**
 * Adds attributes to `<script>` tag inside html file generated by
 * HTMLWebpackPlugin. Used to add `crossorigin="anonymous"`.
 */
export function crossOriginScriptTagPlugin(): webpack.WebpackPluginInstance {
    return new ScriptExtHtmlWebpackPlugin({
        custom: {
            test: /\.js$/,
            attribute: "crossorigin",
            value: "anonymous",
        },
    }) as any;
}
