packages:
    - packages/**
    - "!**/test/**"
    - "!**/build/**"
    - "!**/dist/**"
# minimumReleaseAge: 4320 TODO/Ian: Add back for master branch
onlyBuiltDependencies:
    - "@swc/core"
    - es5-ext
    - esbuild
    - ttf2woff2
