packages:
    - packages/**
    - "!**/test/**"
    - "!**/build/**"
    - "!**/dist/**"
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
    - "@pinnacle0/*"
    - "swc-plugin-core-fe-hmr"
    - "minimatch"
onlyBuiltDependencies:
    - "@swc/core"
    - es5-ext
    - esbuild
    - ttf2woff2
