/*
-----------------------------------------------------------------------------
                Attention: This file is generated by codegen
                          Do not modify by hand
-----------------------------------------------------------------------------
*/
export type ModType = "react-util-to-web-ui";
