/*
-----------------------------------------------------------------------------
                Attention: This file is generated by codegen
                          Do not modify by hand
-----------------------------------------------------------------------------
*/
export type ModType = "use-react-hook-from-web-ui" | "use-react-util-from-web-ui";
