// -----------------------------------------------------------------------------
//      Attention: This file is generated by "yarn export-rules-and-config"
//                           Do not modify by hand
//              Run "yarn export-rules" to regenerate this file
// -----------------------------------------------------------------------------

import {RuleListener, RuleModule} from "@typescript-eslint/experimental-utils/dist/ts-eslint";
// {{TEMPLATE_IMPORT_STATEMENTS}}

export const rules: Record<string, RuleModule<string, any[], RuleListener>> = {
    // {{TEMPLATE_RULE_DEFINITIONS}}
};
