// -----------------------------------------------------------------------------
//      Attention: This file is generated by "codegen" script
//                           Do not modify by hand
//              Run "codegen" script to regenerate this file
// -----------------------------------------------------------------------------

import type {TSESLint} from "@typescript-eslint/utils";
// {{TEMPLATE_IMPORT_STATEMENTS}}

export const rules: Record<string, TSESLint.RuleModule<string, any[], any, TSESLint.RuleListener>> = {
    // {{TEMPLATE_RULE_DEFINITIONS}}
};
