// -----------------------------------------------------------------------------
//      Attention: This file is generated by "yarn export-rules-and-config"
//                           Do not modify by hand
//              Run "yarn export-rules" to regenerate this file
// -----------------------------------------------------------------------------

import type {TSESLint} from "@typescript-eslint/experimental-utils";
// {{TEMPLATE_IMPORT_STATEMENTS}}

export const rules: Record<string, TSESLint.RuleModule<string, any[], TSESLint.RuleListener>> = {
    // {{TEMPLATE_RULE_DEFINITIONS}}
};
