name: "@pinnacle0/util CI"

env:
    CI: true

on:
    push:
        branches: [master, pnpm]
        paths:
            - packages/util/**
            - .github/workflows/pkg-util-ci.yml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  check-latest: true
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm --filter @pinnacle0/util run build
