name: "@pinnacle0/devtool-util CI"

env:
    CI: true

on:
    push:
        branches: [master, pnpm]
        paths:
            - packages/devtool-util/**
            - package.json
            - pnpm-lock.yaml
            - pnpm-workspace.yaml
            - .github/workflows/pkg-devtool-util-ci.yml
            - tsconfig.base.json

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
              with:
                  version: latest

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  check-latest: true
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm --filter @pinnacle0/devtool-util run build
